change man page to describe directory & file exclusions

diff --git a/usr/bin/bodhibuilder b/usr/bin/bodhibuilder
--- a/usr/bin/bodhibuilder
+++ b/usr/bin/bodhibuilder
@@ -51,57 +51,70 @@ fi
 
 
 ##### FUNCTION helper #####
-helper () {
+#~ helper () {
 
-less << FOO
-Usage of bodhibuilder $BODHIBUILDERVERSION is as follows:
+#~ less << FOO
+#~ Usage of bodhibuilder $BODHIBUILDERVERSION is as follows:
 
-   sudo bodhibuilder -b|-c|-d|backup|clean|dist [[custom.iso]|[cdfs]|[iso custom.iso]]
+   #~ sudo bodhibuilder -b|-c|-d|backup|clean|dist [[custom.iso]|[cdfs]|[iso custom.iso]]
 
-See the file /etc/bodhibuilder.conf for more configuration options.
+#~ See the file /etc/bodhibuilder.conf for more configuration options.
 
-Add custom repositories and the comments for them to the file 
-   /etc/bodhibuilder/apt/custom_repos
-   and during firstboot of the newly installed OS, this entire file 
-   will be appended to /etc/apt/sources.list.
-   * Be sure not to add repositories to this file that are already in /etc/apt/sources.list
-     otherwise you will have duplicate entries in /etc/apt/sources.list and the system
-     won't like it.
-
-
-Usage examples:
-
-   sudo bodhibuilder backup                (to make a livecd/dvd backup of your system)
-   sudo bodhibuilder -b
-
-   sudo bodhibuilder backup custom.iso     (to make a livecd/dvd backup and call the iso custom.iso)
-   sudo bodhibuilder -b custom.iso
-
-   sudo bodhibuilder clean                 (to clean up temporary files of bodhibuilder)
-   sudo bodhibuilder -c
-
-   sudo bodhibuilder dist                  (to make a distributable livecd/dvd of your system)
-   sudo bodhibuilder -d
-
-   sudo bodhibuilder dist cdfs             (to make a distributable livecd/dvd filesystem only)
-   sudo bodhibuilder -d cdfs
-
-   sudo bodhibuilder dist iso custom.iso   (to make a distributable iso named custom.iso but only
-   sudo bodhibuilder -d iso custom.iso      if the cdfs is already present)
-
-   cdfs and iso options should only be used if you wish to modify something on the
-   cd before the iso is created.  An example of this would be to modify the isolinux
-   portion of the livecd/dvd
+   #~ The directory & file excludes are as follows:
    
-   sudo bodhibuilder version               (reports the current version of bodhibuilder)
-   sudo bodhibuilder -v
+     #~ Use absolute paths (from the root directory)
+     #~ Exclude specific files using the path to the file = /path/to/file
+     #~ Exclude specific directories using a trailing slash = /path/to/directory/
+     #~ Exclude all directory contents with an asterisk = /path/to/directory/*
+     #~ Exclude all matching sets of files or directories using an asterisk as a wildcard = /path/to/something*
+     #~ If the entry does not exist as an actual file or directory, rsync & mksquashfs will simply skip over it
+     #~ Separate each entry with a space
 
-   sudo bodhibuilder-gtk                   (use the graphical version of bodhibuilder)
+#~ Add custom repositories and the comments for them to the file 
 
-   >> Type "Q" at any time to exit this help <<
+   #~ /etc/bodhibuilder/apt/custom_repos
+   
+   #~ and during firstboot of the newly installed OS, this entire file 
+   #~ will be appended to /etc/apt/sources.list.
+   
+   #~ * Be sure not to add repositories to this file that are already in /etc/apt/sources.list
+     #~ otherwise you will have duplicate entries in /etc/apt/sources.list and the system
+     #~ won't like it.
 
-FOO
-}
+
+#~ Usage examples:
+
+   #~ sudo bodhibuilder backup                (to make a livecd/dvd backup of your system)
+   #~ sudo bodhibuilder -b
+
+   #~ sudo bodhibuilder backup custom.iso     (to make a livecd/dvd backup and call the iso custom.iso)
+   #~ sudo bodhibuilder -b custom.iso
+
+   #~ sudo bodhibuilder clean                 (to clean up temporary files of bodhibuilder)
+   #~ sudo bodhibuilder -c
+
+   #~ sudo bodhibuilder dist                  (to make a distributable livecd/dvd of your system)
+   #~ sudo bodhibuilder -d
+
+   #~ sudo bodhibuilder dist cdfs             (to make a distributable livecd/dvd filesystem only)
+   #~ sudo bodhibuilder -d cdfs
+
+   #~ sudo bodhibuilder dist iso custom.iso   (to make a distributable iso named custom.iso but only
+   #~ sudo bodhibuilder -d iso custom.iso      if the cdfs is already present)
+
+   #~ cdfs and iso options should only be used if you wish to modify something on the
+   #~ cd before the iso is created.  An example of this would be to modify the isolinux
+   #~ portion of the livecd/dvd
+   
+   #~ sudo bodhibuilder version               (reports the current version of bodhibuilder)
+   #~ sudo bodhibuilder -v
+
+   #~ sudo bodhibuilder-gtk                   (use the graphical version of bodhibuilder)
+
+   #~ >> Type "Q" at any time to exit this help <<
+
+#~ FOO
+#~ }
 ##### END function helper #####
 
 
@@ -124,8 +137,10 @@ case $1 in
         exit 0
     ;;
     * )
-        helper
+        man bodhibuilder
         exit 1
+        #~ helper
+        #~ exit 1
     ;;
 esac
 
@@ -312,8 +327,10 @@ case $1  in
         OPT1="dist"
     ;;
     * )
-        helper
+        man bodhibuilder
         exit 1
+        #~ helper
+        #~ exit 1
     ;;
 esac
 
